# This file is part of REANA.
# Copyright (C) 2017, 2018 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: true

language: python

cache:
  - pip

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: REQUIREMENTS=devel EXTRAS=all
    - python: 2.7
      env: REQUIREMENTS=lowest EXTRAS=all
    - python: 2.7
      env: REQUIREMENTS=release EXTRAS=all
    - python: 3.6
      env: REQUIREMENTS=devel EXTRAS=all
    - python: 3.6
      env: REQUIREMENTS=lowest EXTRAS=all
    - python: 3.6
      env: REQUIREMENTS=release EXTRAS=all
    - python: 3.7
      env: REQUIREMENTS=devel EXTRAS=all
    - python: 3.7
      env: REQUIREMENTS=lowest EXTRAS=all
    - python: 3.7
      env: REQUIREMENTS=release EXTRAS=all
    - python: 3.8
      env: REQUIREMENTS=devel EXTRAS=all
    - python: 3.8
      env: REQUIREMENTS=lowest EXTRAS=all
    - python: 3.8
      env: REQUIREMENTS=release EXTRAS=all

before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls requirements-builder
  # requirements-builder in python2 only works with click<=7.0
  - travis_retry pip install click==7.0
  - requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt
  - requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt
  - requirements-builder -e $EXTRAS --level=dev --req requirements-dev.txt setup.py > .travis-devel-requirements.txt
  - travis_retry pip uninstall click -y

install:
  - pip install -r requirements-dev.txt
  - travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt
  - travis_retry pip install -e .[$EXTRAS]

script:
  - ./run-tests.sh

after_success:
  - coveralls
